steps:
#First Clone from Google Cloud Source Repository  
- name: 'gcr.io/cloud-builders/git'
# args: ['clone','https://source.developers.google.com/p/${_PROJECT}/r/${_REPO_NAME}']
  args: ['clone', 'https://github.com/ajaynaphade969/cicd-service.git']

#Build the image 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}','.']

#Push the image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}']
  
#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['builds', 'submit', '--tag', 'gcr.io/${_PROJECT}/cloudbuild-demo-image:${_VERSION}','.']

#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENTNAME}'
  - 'hello-cloudbuild-demo-app-sha256-1=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
substitutions:
    #GCP Specific configuration. Please DON'T change anything
    _PROJECT: gcp-ngt-training
    _ZONE: us-central1-c
    _GKE_CLUSTER: cloudbuild-demo-cluster

    #Repository Specific configuration. DevOps can change this settings
    _DEPLOYMENTNAME: hello-cloudbuild-demo-app
    _CONTAINERNAME: hello-cloudbuild-demo-app
    _REPO_NAME: cicd-service

    # Developers ONLY change
    _VERSION: v1.0

options:
    substitution_option: 'ALLOW_LOOSE'
    logging: CLOUD_LOGGING_ONLY

