apiVersion: v1
kind: Service
metadata:
  name: hello-cloudbuild-demo-app
  namespace: default
spec:
    ports:
    - name: http
      port: 8080
      targetPort: 8080
    type: LoadBalancer
    selector:
     app: hello-cloudbuild-demo-app